### ISSUE TITLE
PathDeleter Recipe Error - Sal.munki

### ISSUE THREAD

**Issue by herdsonb01** [autopkg/grahamgilbert-recipes#30]
Not sure if this is related to the recipe cache being on a mounted volume, but it won't properly complete and has the following Recipe error (copied from receipt plist):

Error in local.munki.Sal: Processor: PathDeleter: Error: Could not remove /Volumes/ceomunkirepo/autopkg/cache/local.munki.Sal/unpack: [Errno 2] No such file or directory: '/Volumes/ceomunkirepo/autopkg/cache/local.munki.Sal/unpack/Scripts/._postinstall'

**Comment by grahamgilbert** [comment]
It’s likely the format of the volume, since it’s referring to a resource fork. Either way, this would be an issue with autopkg itself rather than the recipe.

**Comment by herdsonb01** [comment]
Thanks Graham! Yes, looks to be how PathDeleter in AutoPkg expects to be working on mac. I'm experimenting with the vfs_fruit module on samba, and so far this seems to be successful with AutoPkg cache, etc.. on my mounted volume.
