### ISSUE TITLE
Question RE ShardOverTimeProcessor

### ISSUE THREAD

**Issue by apizz** [autopkg/grahamgilbert-recipes#32]
RE https://github.com/autopkg/grahamgilbert-recipes/blob/master/ShardOverTimeProcessor/ShardOverTimeProcessor.py, I wasn't clear on the processor's use case. Does this have to be in a recipe proper, or could it be used as a post processor?

**Comment by grahamgilbert** [comment]
Put it in your override

**Comment by apizz** [comment]
10-4. Thanks
