### ISSUE TITLE
outset failure

### ISSUE THREAD

**Issue by stefanj135** [autopkg/grahamgilbert-recipes#36]
Hi Graham,
Getting this failure when im running Outset. Looks like the pkg_payload_path is a problem. Unsure on how to fix.

The following recipes failed:
    outset.munki
        Error in local.munki.outset: Processor: PkgPayloadUnpacker: Error: extraction of /srv/autopkg/Cache/local.munki.outset/unpack/Payload with ditto failed: ditto: /srv/autopkg/Cache/local.munki.outset/unpack/Payload: No such file or directory

PkgPayloadUnpacker
{'Input': {'destination_path': '/srv/autopkg/Cache/local.munki.outset/payload',
           'pkg_payload_path': '/srv/autopkg/Cache/local.munki.outset/unpack/Payload'}}
extraction of /srv/autopkg/Cache/local.munki.outset/unpack/Payload with ditto failed: ditto: /srv/autopkg/Cache/local.munki.outset/unpack/Payload: No such file or directory

**Comment by homebysix** [comment]
@stefanj135 Have you done a `repo-update` lately? The error you're seeing sounds a lot like what one might experience if they didn't have [this fix](https://github.com/autopkg/grahamgilbert-recipes/commit/ec7caab1a11ddc1c0454870c0c8501d68553b814#diff-a1d49fbc886623b0567058f94a39b1719c15371077222d798db165f212033436) from October applied yet.

**Comment by stefanj135** [comment]
Thanks for the prompt @homebysix sadly a rookie error. I should have done that before raising an issue. All sorted :)
