### ISSUE TITLE
Outset - Installs Array fails to generate. 

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/grahamgilbert-recipes#57]
Hi, @grahamgilbert 

The outset munki recipe is currently failing to generate the installs array. 

```
MunkiInstallsItemsCreator
PathDeleter
PathDeleter: Deleted /Users/paul.cossey/Library/AutoPkg/Cache/com.github.grahamgilbert.munki.outset/unpack
PathDeleter: Deleted /Users/paul.cossey/Library/AutoPkg/Cache/com.github.grahamgilbert.munki.outset/payload
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {'installs': []} into pkginfo
MunkiImporter
```

I had planned on raising a PR to resolve, but it turned out to be a bit more of a pain than original anticipated, I wanted to keep the originally intended functionality of having the launch d's and binary in the installs array, and add the Outset.app but use `CFBundleVersion` as the comparison key. (Slack thread here: https://macadmins.slack.com/archives/C056155B4/p1732214788477269) 

I ended up needing a custom processor to change the comparison key to `CFBundleVersion` - it didn't feel right expecting you to maintain code you didn't write so I rolled our own recipes based on yours: https://github.com/autopkg/dataJAR-recipes/tree/master/Outset 

Not sure if you want to deprecate/fix yours or whether you're happy with current functionality with the pkg receipt?

**Comment by grahamgilbert** [comment]
I don't use this anymore, we have our own tool that provides this functionality. I'm fine with a PR with a depreciation notice in.

**Comment by paul-cossey** [comment]
Done! https://github.com/autopkg/grahamgilbert-recipes/pull/58
